### PR TITLE
Added library to laod mody from zip files

### PR DESCRIPTION
**Pull request by komaflash**
Hi mates,

Alfredo asked me to add my mod load library from ModCommander. - Here you go.
Somebody maybe know me as ec8or from modhoster.

### CODE REVIEW

**Comment by Madbros** [comment]
Thank you, I'll take a look, not sure if we can mix your C code whit our VB code? Any help would be appreciated. We use VS2013

**Comment by komaflash** [comment]
Hi,

yes for sure. You can always combine any managed code librarys. F#, C#,
VB.NET, ...

ec8or//Malte

**Comment by komaflash** [comment]
I just saw that you use VS2010, Alfredo told me you use VS2013. Maybe you can't open it with 2010, cause the solution was migrated to 2013, see https://github.com/PromGames/Coursedrawer/blob/3aed6bf8d189d4f77d1465b87ab0e14be08e664a/CourseDrawer.sln

-Microsoft Visual Studio Solution File, Format Version 11.00
-# Visual Basic Express 2010

**Comment by PromGames** [comment]
We are using VS2013, but the original programme was writtrn in 2010. May be
that is the reason. We will try to run it enterily in 2013.

In fact, we have tried to use DevIL and we don get it to work with our
picture box to load a.dds file instead of a .bmp. Maybe this is the reason
and you are able to make DEVIL or RESIL works.

Tell you tomorrow

2015-01-22 22:35 GMT+01:00 komaflash <notifications@github.com>:

**Comment by komaflash** [comment]
Just a note to DevIL: It runs only in x86 and you have to copy the unmanaged DLL into you bin directory, as it will not be done by VS. I simple created a PostBuild command to get things working and copy the stuff i need.

**Comment by PromGames** [comment]
Yes, I saw it. Is working fine now in the new version.

We are having problems with the comand of scaling in DEVIl, but we are doing afterwards as we are loading the picture box with bmp anyway. Then we will scale the BMp

We also have changed the layout to metro form. And now is also sensible to touchscreen.
But we are in the middle of the process. 

I've go a good collection of templates for windows forms if you are interested. You can see it in dotnetbar forms.

We will use also the zip sharp lib

Now we are treating data. We are thinking using data set, let's see.

Big issue trying to make the undo redo process , mainly when we draw the courses or WP.

But everything looks very promising.

Alfredo Prieto

**Pull request merged**
